name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Package
        run: npm i -g vsce && npm install && vsce package
      - run: vsce publish -p ${{secrets.VSCE}}
        env:
          VSCE: ${{secrets.VSCE}}